name: Extract VM details

on: workflow_dispatch

jobs: 
  extract-data:
   runs-on: ubuntu-latest
   steps:
     - name: create sample Json
       run: |
        echo '{
         "instance_id": "xyz123456",
         "public_ip_address": "192.168.1.10",
         "private_ip": "198.56.2.3",
         "instance_type": "t2_micro"
        }' > data.json

     - name: extract the values
       run: |
        INSTANCE_ID=$( jq -r .'instance_id' data.json )
        PUBLIC_IP=$( jq -r .'public_ip_address' data.json )
        INSTANCE_TYPE=$( jq -r .'instance_type' data.json )

        echo "INSTANCE_ID=$INSTANCE_ID >> GITHUB_ENV
        echo "PUBLIC_IP=$PUBLIC_IP >> GITHUB_ENV
        echo "INSTANCE_ID=$INSTANCE_ID >> GITHUB_ENV

     - name: print values
       run: |
        echo "INSTANCE_ID=$INSTANCE_ID 
        echo "PUBLIC_IP=$PUBLIC_IP 
        echo "INSTANCE_ID=$INSTANCE_ID 

      
        
        
   
    
