name: Jq install and extract Data

on: 
 push: 
  branches: main
 workflow_dispatch:

jobs:
 jq-extract-data:
   name: jq install 
   runs-on: ubuntu-latest
   steps:
    - name: Install JQ
      run: |
       sudo apt-get install -y jq
       jq --version

    - name: Create JSON Data
      run: |
       cat << EOF > data.json
        {
            "public_ip": "192.168.1.100",
            "email": "admin@example.com",
            "uuid": "123e4567-e89b-12d3-a456-426614174000"
        }
        EOF 
     
    - name: Extract data
      run: |
       EMAIL_ID=$(jq -rc '.email' data.json)
       echo $EMAIL_ID
       
    
   
