name: Nested Json Data

on: workflow_dispatch

jobs:
  nested-data:
   runs-on: ubuntu-latest
   steps: 
      - name: Create nested Data
        run: |
         echo '{
         "Reservations": [
          { 
            "Instances": [
              {
                "Instance_id":"123456789",
                "state": {"Name": "Running"},
                "publicipaddress": "192.168.10.2.2"
              
              }
            
            ]
          }
         ]
         }' > data.json
         cat data.json
    
      - name: Extract Data
        run: |
         INSTANCE_ID=$( jq -r '.Reservations[0].Instances[0].Instance_id' data.json)
         Sate_ID=$( jq -r '.Reservations[0].Instances[0].state.Name' data.json)
         PUBLIC_IP=$( jq -r '.Reservations[0].Instances[0].publicipaddress' data.json)
         echo INSTANCE_ID=$INSTANCE_ID
         echo State_ID=$State_ID
         echo PUBLIC_ID=$PUBLIC_IP
      
